"""
italian_daily_bot.py
---------------------
Sends 10 new Italian words/expressions (A2/B1) to a Telegram channel every day,
generated by Claude Haiku. Translations in English + German, 3 example sentences
each, plus a short mini-review with 3 questions.

Credentials are read from environment variables.
  - Locally:  a .env file (loaded by python-dotenv) provides them.
  - On GitHub Actions: repository Secrets provide them.
The .env file must NEVER be committed to GitHub (see .gitignore).

Run modes:
    python3 italian_daily_bot.py --once     # generate + send once (used by GitHub Actions)
    python3 italian_daily_bot.py            # local loop, sends daily at SEND_TIME

Requirements:
    pip3 install requests python-dotenv schedule
"""

import re
import os
import json
import html
import time
import argparse

import requests
from dotenv import load_dotenv

# Load variables from a local .env file if present (does nothing on GitHub Actions).
load_dotenv()

# --------------------------------------------------------------------------- #
#  CREDENTIALS  — read from environment (.env locally / Secrets on GitHub)
# --------------------------------------------------------------------------- #
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID   = os.environ.get("TELEGRAM_CHAT_ID", "")
ANTHROPIC_API_KEY  = os.environ.get("ANTHROPIC_API_KEY", "")

# --------------------------------------------------------------------------- #
#  CONFIG  — tweak these without touching the logic below
# --------------------------------------------------------------------------- #
MODEL        = "claude-haiku-4-5-20251001"   # cheapest current tier
LEVEL        = "A2/B1"
WORDS_PER_DAY = 5
MAX_TOKENS   = 4000          # 10 words with trilingual examples need room
TEMPERATURE  = 0.7

# SEND_TIME only applies to the LOCAL loop mode. On GitHub Actions the schedule
# is controlled by the cron line in .github/workflows/italian-daily.yml instead.
SEND_TIME    = "08:00"        # 24h, local machine time
SEEN_FILE    = "seen_words.json"
AVOID_RECENT = 60            # how many recently-taught words to tell Claude to avoid

TELEGRAM_MSG_LIMIT = 4096
SAFE_CHUNK         = 3800     # leave margin below the hard limit

ANTHROPIC_URL = "https://api.anthropic.com/v1/messages"

# --------------------------------------------------------------------------- #
#  PROMPT
# --------------------------------------------------------------------------- #
SYSTEM_PROMPT = f"""You are my Italian teacher for {LEVEL} level.

Each day you produce {WORDS_PER_DAY} new Italian words or useful expressions at {LEVEL} level.
Choose practical vocabulary for daily life in Italy, university, work, travel,
communication, and bureaucracy. Avoid very rare or literary words.
Do NOT conjugate verbs (give the infinitive/base form only).
Do NOT include any Farsi.

Return ONLY valid JSON, no markdown, no code fences, no commentary, in exactly this shape:
{{
  "words": [
    {{
      "italian": "the word or expression",
      "english": "English translation",
      "german": "German translation",
      "usage": "short usage note, or empty string if not useful",
      "examples": [
        {{"it": "...", "en": "...", "de": "..."}},
        {{"it": "...", "en": "...", "de": "..."}},
        {{"it": "...", "en": "...", "de": "..."}}
      ]
    }}
  ],
  "review": {{
    "questions": ["question 1", "question 2", "question 3"]
  }}
}}

Rules:
- Exactly {WORDS_PER_DAY} items in "words".
- Exactly 3 example sentences per word, each natural and {LEVEL}-appropriate.
- The mini-review has exactly 3 short questions that test today's words.
- No Farsi anywhere. No conjugation tables."""


def build_user_message(avoid_words):
    msg = f"Give me today's {WORDS_PER_DAY} new Italian words/expressions."
    if avoid_words:
        joined = ", ".join(avoid_words)
        msg += (f"\n\nDo NOT repeat any of these recently taught words "
                f"(pick different ones): {joined}")
    return msg


# --------------------------------------------------------------------------- #
#  SEEN-WORDS STORE  (avoids daily repetition)
# --------------------------------------------------------------------------- #
def load_seen():
    if os.path.exists(SEEN_FILE):
        try:
            with open(SEEN_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            return []
    return []


def save_seen(seen):
    with open(SEEN_FILE, "w", encoding="utf-8") as f:
        json.dump(seen, f, ensure_ascii=False, indent=2)


# --------------------------------------------------------------------------- #
#  CLAUDE
# --------------------------------------------------------------------------- #
def generate_lesson(avoid_words):
    headers = {
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
    }
    payload = {
        "model": MODEL,
        "max_tokens": MAX_TOKENS,
        "temperature": TEMPERATURE,
        "system": SYSTEM_PROMPT,
        "messages": [{"role": "user", "content": build_user_message(avoid_words)}],
    }

    resp = requests.post(ANTHROPIC_URL, headers=headers, json=payload, timeout=120)
    resp.raise_for_status()
    data = resp.json()

    raw = "".join(block.get("text", "") for block in data.get("content", []))
    raw = raw.strip()

    # strip code fences if the model adds them despite instructions
    raw = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw).strip()

    lesson = json.loads(raw)
    if "words" not in lesson or not lesson["words"]:
        raise ValueError("Lesson JSON missing 'words'.")
    return lesson


# --------------------------------------------------------------------------- #
#  FORMATTING  ->  list of Telegram-safe HTML messages
# --------------------------------------------------------------------------- #
def esc(text):
    """Escape user/AI text for Telegram HTML parse mode."""
    return html.escape(str(text or ""), quote=False)


def format_word_block(index, w):
    lines = [f"<b>{index}. {esc(w.get('italian'))}</b>"]
    lines.append(f"\U0001F1EC\U0001F1E7 {esc(w.get('english'))}")
    lines.append(f"\U0001F1E9\U0001F1EA {esc(w.get('german'))}")
    if w.get("usage"):
        lines.append(f"\U0001F4A1 <i>{esc(w['usage'])}</i>")
    lines.append("")  # spacer
    for ex in w.get("examples", []):
        lines.append(f"\U0001F1EE\U0001F1F9 {esc(ex.get('it'))}")
        lines.append(f"   \U0001F1EC\U0001F1E7 {esc(ex.get('en'))}")
        lines.append(f"   \U0001F1E9\U0001F1EA {esc(ex.get('de'))}")
    return "\n".join(lines)


def build_messages(lesson):
    """Group word blocks into messages under the Telegram size limit."""
    header = "\U0001F4DA <b>Italiano del giorno \u2014 A2/B1</b>\n\n"
    blocks = [format_word_block(i + 1, w) for i, w in enumerate(lesson["words"])]

    messages = []
    current = header
    for block in blocks:
        candidate = current + block + "\n\n"
        if len(candidate) > SAFE_CHUNK:
            messages.append(current.rstrip())
            current = block + "\n\n"
        else:
            current = candidate
    if current.strip():
        messages.append(current.rstrip())

    # mini-review as its own message
    review = lesson.get("review", {}).get("questions", [])
    if review:
        rlines = ["\U0001F4DD <b>Mini-review</b>\n"]
        for i, q in enumerate(review, 1):
            rlines.append(f"{i}. {esc(q)}")
        messages.append("\n".join(rlines))

    return messages


# --------------------------------------------------------------------------- #
#  TELEGRAM
# --------------------------------------------------------------------------- #
def send_telegram(text):
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": text,
        "parse_mode": "HTML",
        "disable_web_page_preview": True,
    }
    resp = requests.post(url, json=payload, timeout=30)
    resp.raise_for_status()
    return resp.json()


# --------------------------------------------------------------------------- #
#  ORCHESTRATION
# --------------------------------------------------------------------------- #
def run_once():
    if not (TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID and ANTHROPIC_API_KEY):
        raise SystemExit(
            "Missing credentials. Set TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID, "
            "and ANTHROPIC_API_KEY in your .env file (local) or GitHub Secrets (cloud)."
        )

    seen = load_seen()
    avoid = seen[-AVOID_RECENT:]

    print("Generating lesson with Claude...")
    lesson = generate_lesson(avoid)

    messages = build_messages(lesson)
    print(f"Sending {len(messages)} message(s) to Telegram...")
    for i, msg in enumerate(messages):
        send_telegram(msg)
        if i < len(messages) - 1:
            time.sleep(1)  # gentle pacing, avoids rate limits

    new_words = [w.get("italian", "") for w in lesson["words"] if w.get("italian")]
    seen.extend(new_words)
    save_seen(seen)
    print(f"Done. Added {len(new_words)} words to {SEEN_FILE}.")


def run_scheduled():
    import schedule
    schedule.every().day.at(SEND_TIME).do(run_once)
    print(f"Scheduler running. Daily send at {SEND_TIME}. Ctrl+C to stop.")
    while True:
        schedule.run_pending()
        time.sleep(30)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Daily Italian vocab Telegram bot")
    parser.add_argument("--once", action="store_true",
                        help="Generate and send a single lesson now, then exit.")
    args = parser.parse_args()

    if args.once:
        run_once()
    else:
        run_scheduled()
