"""
language_daily_bot.py
---------------------
Sends a daily language-learning lesson to a Telegram channel, generated by
Claude Haiku, and lets you feed it your own words over Telegram.

Main focus is RECALLING everyday German (A2/B1) after a long gap — practical,
spoken, daily language, not advanced/formal register. On top of that you can
DM the bot words of your own (German, Italian, English, or Japanese) and they
get PRIORITY: each day's 5 word slots are filled with your queued words first,
then topped up with fresh auto-generated German.

Each day's message contains:
  - Up to 5 words. Your added words first (taught in their own language), then
    auto-generated German to fill the remaining slots (easiest first:
    A2, A2, B1, B1, B2). Nouns include their article + plural (de/it); Japanese
    words include kana + romaji readings.
  - A few REVIEW words resurfacing on a spaced-repetition schedule
    (roughly 1 -> 3 -> 7 -> 16 -> 35 -> 90 days after each successful review).
  - One short German grammar tip, cycling through a fixed B1 curriculum.
  - One voice note per language present that day (headwords + example
    sentences read aloud via Microsoft Edge TTS). Only target-language text
    is spoken; English glosses are never sent to TTS.

Two-way input:
  You DM the bot (from your own Telegram account only) words to learn, e.g.
      it: frigorifero, lavatrice
      ja: 冷蔵庫
      en: reliable
  Untagged text defaults to German. Japanese script is auto-detected. The bot
  reads these on its next run via getUpdates, queues them, and confirms by DM.
  It ONLY ever reacts to messages from ALLOWED_USER_ID — everything else is
  ignored.

State (vocab SRS schedule, grammar position, your pending word queue, and the
Telegram update offset) lives in progress.json, which the GitHub Actions
workflow commits back to the repo after every successful run.

Credentials are read from environment variables.
  - Locally:  a .env file (loaded by python-dotenv) provides them.
  - On GitHub Actions: repository Secrets provide them.
The .env file must NEVER be committed to GitHub (see .gitignore).

Run modes:
    python3 language_daily_bot.py --once      # generate + send once (GitHub Actions)
    python3 language_daily_bot.py --dry-run   # build a sample lesson, print it, send NOTHING
    python3 language_daily_bot.py             # local loop, sends daily at SEND_TIME

Requirements:
    pip3 install requests python-dotenv schedule edge-tts
    ffmpeg must also be installed and on PATH (used to convert the TTS
    output into the ogg/opus format Telegram voice notes require).
"""

import re
import os
import json
import html
import time
import asyncio
import argparse
import tempfile
import subprocess
from datetime import date, timedelta

import requests
import edge_tts
from dotenv import load_dotenv

load_dotenv()

# --------------------------------------------------------------------------- #
#  CREDENTIALS  — read from environment (.env locally / Secrets on GitHub)
# --------------------------------------------------------------------------- #
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID   = os.environ.get("TELEGRAM_CHAT_ID", "")   # channel that lessons post to
ANTHROPIC_API_KEY  = os.environ.get("ANTHROPIC_API_KEY", "")

# The ONLY Telegram user the bot accepts words/commands from. Keyed on the
# numeric user id (usernames can change). Overridable via env, defaults to you.
ALLOWED_USER_ID = int(os.environ.get("TELEGRAM_ALLOWED_USER_ID", "142201469"))

# --------------------------------------------------------------------------- #
#  CONFIG
# --------------------------------------------------------------------------- #
MODEL         = "claude-haiku-4-5-20251001"   # cheapest current tier
LEVEL         = "A2/B1"
EXAMPLE_LEVEL = "B1/B2"      # example sentences are pitched a notch above word level

# ---- DAILY WORD MIX --------------------------------------------------------
# Total words taught per day. YOUR queued words are used first; whatever slots
# remain are filled with auto-generated GERMAN words, taken from the priority
# list below (easiest first — the B2 "stretch" word only shows if there's room).
WORDS_PER_DAY      = 5
GERMAN_AUTO_SLOTS  = ["A2", "A2", "B1", "B1", "B2"]
REVIEW_PER_DAY_TARGET = 2   # review words on top of the new ones (when due)

# You asked to focus on German only for now — Turkish output is switched off.
# Flip this back to True to re-enable Turkish translations everywhere.
INCLUDE_TURKISH = False
# ----------------------------------------------------------------------------

# ---- LANGUAGES -------------------------------------------------------------
SUPPORTED_LANGS  = ["de", "it", "en", "ja"]
DEFAULT_ADD_LANG = "de"      # untagged added words are treated as German
LANG_NAMES = {"de": "German", "it": "Italian", "en": "English", "ja": "Japanese"}
LANG_FLAGS = {"de": "🇩🇪", "it": "🇮🇹", "en": "🇬🇧", "ja": "🇯🇵"}
# Free Microsoft Edge TTS neural voices, one per language.
VOICES = {
    "de": "de-DE-KatjaNeural",
    "it": "it-IT-ElsaNeural",
    "en": "en-US-AriaNeural",
    "ja": "ja-JP-NanamiNeural",
}
# Any run of these characters marks a word as Japanese even without a "ja:" tag.
JP_CHAR_RE = re.compile(r"[぀-ヿ㐀-䶿一-鿿ｦ-ﾟ]")
# Leading definite/indefinite articles stripped from added de/it nouns, so the
# stored headword is clean (the article belongs in its own field when taught).
ARTICLES = {
    "de": {"der", "die", "das", "den", "dem", "des", "ein", "eine", "einen", "einem", "einer"},
    "it": {"il", "lo", "la", "i", "gli", "le", "un", "uno", "una"},
}
# ----------------------------------------------------------------------------

# ---- VOICE (Microsoft Edge TTS) --------------------------------------------
ENABLE_VOICE = True
# ----------------------------------------------------------------------------

# Spaced-repetition intervals, in days, after the 1st/2nd/3rd/... successful
# review of a word. Stays at the last value for further reviews.
REVIEW_INTERVALS = [1, 3, 7, 16, 35, 90]

MAX_TOKENS   = 6000   # English-only output; raise if you re-enable Turkish
TEMPERATURE  = 0.7

SEND_TIME     = "08:00"        # 24h, local machine time (only used in loop mode)
PROGRESS_FILE = "progress.json"

TELEGRAM_MSG_LIMIT = 4096
SAFE_CHUNK         = 3800     # leave margin below the hard limit

ANTHROPIC_URL     = "https://api.anthropic.com/v1/messages"
TELEGRAM_API_BASE = "https://api.telegram.org/bot{token}/{method}"

# Fixed B1 grammar curriculum, cycled through one topic per day (~20 days
# per full loop, which doubles as a natural grammar review interval).
GRAMMAR_TOPICS = [
    "Perfekt vs. Präteritum: when to use each in spoken vs. written German",
    "The four cases overview: Nominativ, Akkusativ, Dativ, Genitiv",
    "Dative prepositions: aus, bei, mit, nach, seit, von, zu, gegenüber",
    "Accusative prepositions: durch, für, gegen, ohne, um",
    "Two-way prepositions (Wechselpräpositionen): an, auf, hinter, in, neben, über, unter, vor, zwischen",
    "Word order: the verb in position 2 in main clauses",
    "Word order: verb-final in subordinate clauses (weil, dass, wenn, ob)",
    "Separable verbs (trennbare Verben) and where the prefix goes",
    "Modal verbs: können, müssen, dürfen, sollen, wollen, mögen",
    "Reflexive verbs and reflexive pronouns",
    "Adjective endings after der/die/das",
    "Adjective endings after ein/eine/ein and with no article",
    "Comparative and superlative forms",
    "Relative clauses with der/die/das as relative pronouns",
    "Konjunktiv II basics: würde + infinitive, wäre, hätte, könnte",
    "Passive voice basics: werden + Partizip II",
    "Genitive vs. spoken German 'von' for possession",
    "Time expressions: am, um, im, seit, vor + time",
    "Question words and question word order",
    "Connectors: weil vs. denn, obwohl, trotzdem, deshalb",
]

# --------------------------------------------------------------------------- #
#  PROMPT
# --------------------------------------------------------------------------- #
_TURKISH_RULE = (
    """I am also learning through Turkish, so every English field has a matching
Turkish field ("turkish", "usage_tr", "explanation_tr", and "tr" inside each
example). Produce natural, fluent Türkiye Turkish (not Azerbaijani, not a
word-for-word crib), using proper Turkish characters (ğ, ı, İ, ş, ç, ö, ü)."""
    if INCLUDE_TURKISH else
    "Do NOT include any Turkish or Farsi anywhere in the output."
)

_TR_FIELD_WORD    = '\n      "turkish": "Turkish translation",\n      "usage_tr": "the usage note in Turkish, or empty string",' if INCLUDE_TURKISH else ""
_TR_FIELD_EXAMPLE = ', "tr": "..."' if INCLUDE_TURKISH else ""
_TR_FIELD_GRAMMAR = '\n    "explanation_tr": "the explanation in Turkish",' if INCLUDE_TURKISH else ""

SYSTEM_PROMPT = f"""You are my personal language teacher. My main focus is
RECALLING everyday German at the {LEVEL} level after a long gap — practical,
spoken, daily-life language, NOT advanced or formal register. On some days I
will also hand you specific words I added myself; those may be in German,
Italian, English, or Japanese, and you must teach each in ITS OWN language.

On a given day I may ask you for any of:
  (1) a number of NEW German words at specific levels (A2/B1/B2),
  (2) specific WORDS I ADDED that you must teach (each tagged with its language),
  (3) specific REVIEW words to refresh (each tagged with its language),
  (4) one German grammar tip.

GERMAN calibration (only for the NEW German words YOU generate):
- A2: high-frequency everyday basics I may have forgotten, like: der Termin,
  abholen, die Rechnung, der Schlüssel, sich beeilen, die Verspätung.
- B1: still everyday and practical but a step up, like: die Anmeldung, der
  Vertrag, verschieben, sich erkundigen, der Umzug, die Bewerbung. Situations:
  renting a flat, doctor visits, forms, trains, ordinary work.
- B2 (only when I ask): useful SPOKEN-German B2 a native uses in normal
  conversation, like: sich Gedanken machen, die Voraussetzung, sich gewöhnen an,
  ausgerechnet, zuverlässig. NOT formal business/policy register.
- WRONG at any level — never give words like: der Sachverhalt, der Stellhebel,
  das Regelwerk, die Entgegnung, die Stellungnahme, sich erübrigen. If a word
  mainly appears in reports, meetings-speak, or newspaper commentary, skip it.
- Prefer concrete over abstract.

PER-LANGUAGE conventions — apply to EVERY word you output (new, added, review):
- Always set "language" to one of: de, it, en, ja.
- German (de) and Italian (it) NOUNS: put the definite article in "article"
  (de: der/die/das; it: il/lo/la/l'/i/gli/le) and the plural form in "plural".
  Verbs: give the infinitive. NEVER put the article inside "word".
- Japanese (ja): "word" is the normal written Japanese form (kanji where a
  native would use it). ALWAYS fill "reading" with kana AND romaji, e.g.
  "れいぞうこ (reizōko)". Set "article" and "plural" to null. Give a "reading"
  for every Japanese example sentence too.
- English (en): the headword is English, so "english" must be a clear, plain-
  English DEFINITION (not a translation). Set "article"/"plural"/"reading" null.
- For de/it/ja, "english" is the natural English meaning/translation.
- The ADDED words I give may be written in their native script, in romanized/
  Latin letters (e.g. Japanese "sumimasen"), OR given as an English meaning or
  phrase (e.g. "excuse me"). In every case, produce the natural, correct word in
  the language I tagged: put the proper written form in "word" (Japanese:
  kanji/kana, with romaji in "reading"), never leaving it in Latin letters or as
  the English phrase, and keep the language I tagged. If a meaning maps to more
  than one common word, pick the single most natural everyday one.
- Example sentences are pitched at {EXAMPLE_LEVEL} level in the word's OWN
  language: natural, complete sentences a fluent speaker would actually say,
  comfortable with subordinate clauses and everyday connectors — spoken
  register, not written/formal constructions.

{_TURKISH_RULE}
Do NOT include any Farsi.

Return ONLY valid JSON, no markdown, no code fences, no commentary, in exactly
this shape:
{{
  "new_words": [
    {{
      "language": "de, it, en, or ja",
      "word": "headword WITHOUT its article (e.g. 'Rechnung', never 'die Rechnung'); infinitive if a verb; Japanese written form if ja",
      "level": "A2, B1, or B2 for German words I asked you to generate; empty string otherwise",
      "article": "der/die/das (de) or il/lo/la/l'/i/gli/le (it) if a noun, else null",
      "plural": "the plural form for a de/it noun, else null",
      "reading": "kana + romaji for ja (e.g. 'たべる (taberu)'), else null",
      "english": "English translation (de/it/ja) OR plain-English definition (en)",
      "usage": "short usage/register note in English, or empty string",{_TR_FIELD_WORD}
      "synonyms": ["2-3 synonyms in the SAME language (article for de/it nouns, reading for ja) -- empty list if none"],
      "family": [
        {{"word": "related word from the same root (article for de/it nouns, reading for ja)", "type": "noun/verb/adjective/adverb", "english": "translation"}}
      ],
      "examples": [
        {{"target": "sentence in the word's language", "reading": "reading for ja sentences, else null", "en": "English translation"{_TR_FIELD_EXAMPLE}}},
        {{"target": "...", "reading": null, "en": "..."{_TR_FIELD_EXAMPLE}}},
        {{"target": "...", "reading": null, "en": "..."{_TR_FIELD_EXAMPLE}}}
      ]
    }}
  ],
  "review_words": [
    // SAME shape as new_words, but "word" and "language" MUST exactly match a
    // word I asked you to review -- never invent, translate, or substitute.
  ],
  "grammar_tip": {{
    "topic": "the German topic I gave you",
    "explanation": "2-4 clear, practical sentences in English",{_TR_FIELD_GRAMMAR}
    "examples": [
      {{"target": "German example", "reading": null, "en": "..."{_TR_FIELD_EXAMPLE}}},
      {{"target": "German example", "reading": null, "en": "..."{_TR_FIELD_EXAMPLE}}}
    ]
  }}
}}

Rules:
- Provide EXACTLY the number of NEW German words per level that I request, and
  order "new_words" so any added words I gave come as I listed them, then the
  generated German words easiest-first (A2, then B1, then B2).
- REVIEW words: teach the EXACT "word" and "language" I give — never substitute,
  translate, or change the language (these must match words I already know).
- ADDED words: keep the language I tagged, but resolve the item to the natural
  target word per the rule above (script / romaji / English meaning all allowed).
- "family" lists 2-4 genuinely common derivations from the same root, or [].
- "synonyms" lists 2-3 real, common same-language substitutes, or [].
- Never invent a weak synonym or family entry just to fill a quota.
- Every field must be filled faithfully — same meaning, same register, never
  abbreviated or skipped."""


def build_user_message(german_counts, added_words, review_words, known_words, grammar_topic):
    parts = []

    total_new_de = sum(n for n in german_counts.values() if n > 0)
    if total_new_de:
        breakdown = ", ".join(f"{n} at {lvl} level" for lvl, n in german_counts.items() if n > 0)
        parts.append(f"Generate {total_new_de} NEW German words I haven't seen before: {breakdown}.")
        if known_words:
            parts.append(
                "Do NOT reuse any of these already-covered German words: "
                + ", ".join(known_words)
            )

    if added_words:
        listed = ", ".join(f"{w['word']} ({LANG_NAMES.get(w['language'], w['language'])})" for w in added_words)
        parts.append(
            "Teach these specific words I added myself (keep the language I tagged; "
            "each item may be the word, its romaji, or an English meaning — teach "
            "the natural target-language word). Put them first in \"new_words\": " + listed
        )

    if review_words:
        listed = ", ".join(f"{w['word']} ({LANG_NAMES.get(w['language'], w['language'])})" for w in review_words)
        parts.append(
            "Also give fresh usage notes and 3 new example sentences for exactly "
            "these REVIEW words (use each word and language unchanged): " + listed
        )
    else:
        parts.append('No review words are due yet -- leave "review_words" as an empty list.')

    parts.append(f"German grammar tip topic for today: {grammar_topic}")

    if not total_new_de and not added_words:
        parts.append('No new words are needed today -- leave "new_words" as an empty list.')

    return "\n\n".join(parts)


# --------------------------------------------------------------------------- #
#  PROGRESS STORE  (vocab SRS + grammar position + word queue + update offset)
# --------------------------------------------------------------------------- #
def load_progress():
    data = {"vocab": {}, "grammar_index": 0, "queue": [], "update_offset": 0}
    if os.path.exists(PROGRESS_FILE):
        try:
            with open(PROGRESS_FILE, "r", encoding="utf-8") as f:
                loaded = json.load(f)
            data.update(loaded)
        except (json.JSONDecodeError, OSError):
            pass
    data.setdefault("vocab", {})
    data.setdefault("grammar_index", 0)
    data.setdefault("queue", [])
    data.setdefault("update_offset", 0)
    # Migration: entries created before multi-language support have no language.
    for info in data["vocab"].values():
        info.setdefault("language", "de")
    return data


def save_progress(progress):
    with open(PROGRESS_FILE, "w", encoding="utf-8") as f:
        json.dump(progress, f, ensure_ascii=False, indent=2)


def compute_next_review_date(review_count):
    idx = min(review_count, len(REVIEW_INTERVALS) - 1)
    return (date.today() + timedelta(days=REVIEW_INTERVALS[idx])).isoformat()


def get_due_review_words(vocab, limit):
    """Return up to `limit` due words as {word, language} dicts."""
    today_iso = date.today().isoformat()
    due = [w for w, info in vocab.items() if info.get("next_review", "9999-12-31") <= today_iso]
    due.sort(key=lambda w: vocab[w].get("next_review", ""))
    return [{"word": w, "language": vocab[w].get("language", "de")} for w in due[:limit]]


def update_vocab_after_send(vocab, taught_items, review_items, requested_review):
    """Record newly-taught words and advance SRS state for reviewed ones."""
    today_iso = date.today().isoformat()

    for w in taught_items:
        key = (w.get("word") or "").strip()
        if not key or key in vocab:
            continue
        vocab[key] = {
            "language": w.get("language", "de"),
            "first_seen": today_iso,
            "review_count": 0,
            "next_review": compute_next_review_date(0),
        }

    returned = {(w.get("word") or "").strip() for w in review_items}
    for r in requested_review:
        key = r["word"]
        if key not in vocab:
            continue
        if key in returned:
            vocab[key]["review_count"] = vocab[key].get("review_count", 0) + 1
            vocab[key]["last_reviewed"] = today_iso
            vocab[key]["next_review"] = compute_next_review_date(vocab[key]["review_count"])
        # a requested review word the model didn't return keeps its due date,
        # so it simply comes up again next run instead of being lost

    return vocab


# --------------------------------------------------------------------------- #
#  TWO-WAY INPUT  — read YOUR DMs, queue words, restricted to ALLOWED_USER_ID
# --------------------------------------------------------------------------- #
def _detect_lang(word, tagged):
    if JP_CHAR_RE.search(word):
        return "ja"
    return tagged


def _clean_headword(word, lang):
    """Strip a leading article from de/it nouns so the stored word is clean."""
    if lang == "it" and re.match(r"^l['’]\s*\S", word, flags=re.IGNORECASE):
        return re.sub(r"^l['’]\s*", "", word, flags=re.IGNORECASE).strip()
    tokens = word.split()
    if len(tokens) >= 2 and tokens[0].lower() in ARTICLES.get(lang, set()):
        return " ".join(tokens[1:]).strip()
    return word


def parse_added_words(text):
    """Parse one Telegram message into [(word, language), ...].

    Accepts tagged or plain lines, comma/newline separated, e.g.:
        it: frigorifero, lavatrice
        ja: 冷蔵庫
        reliable            (untagged -> German, unless it's Japanese script)
    """
    results = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        # optional leading "add:" / "add " prefix
        line = re.sub(r"^\s*add[:\s]+", "", line, flags=re.IGNORECASE)

        lang = DEFAULT_ADD_LANG
        m = re.match(r"^\s*(de|it|en|ja)\s*[:\-]\s*(.+)$", line, flags=re.IGNORECASE)
        if m:
            lang = m.group(1).lower()
            line = m.group(2)

        for chunk in re.split(r"[,;]|\s{2,}", line):
            word = chunk.strip().strip("•-–—*").strip()
            if word:
                detected = _detect_lang(word, lang)
                results.append((_clean_headword(word, detected), detected))
    return results


def fetch_new_messages(offset):
    url = TELEGRAM_API_BASE.format(token=TELEGRAM_BOT_TOKEN, method="getUpdates")
    params = {"timeout": 0, "allowed_updates": json.dumps(["message"])}
    if offset:
        params["offset"] = offset + 1
    resp = requests.get(url, params=params, timeout=30)
    resp.raise_for_status()
    return resp.json().get("result", [])


HELP_TEXT = (
    "🗣️ <b>Add words to learn</b>\n"
    "Just send them, one message or several. Tag the language (default German):\n"
    "<code>it: frigorifero, lavatrice</code>\n"
    "<code>ja: 冷蔵庫</code>\n"
    "<code>en: reliable</code>\n"
    "<code>der Kühlschrank</code>  (untagged = German)\n\n"
    "Your words get taught first in the next lessons.\n\n"
    "Commands: /list — show your queue · /help — this message"
)


def _queue_summary(progress):
    q = progress.get("queue", [])
    if not q:
        return "Your queue is empty. Send me some words to learn!"
    lines = [f"📋 <b>{len(q)} word(s) queued</b> (taught in this order):"]
    for i, item in enumerate(q, 1):
        lines.append(f"{i}. {esc(item['word'])} {LANG_FLAGS.get(item['language'], '')}")
    return "\n".join(lines)


def handle_command(text, progress):
    cmd = text.strip().split()[0].lower().lstrip("/")
    cmd = cmd.split("@")[0]   # strip @botname suffix if present
    if cmd in ("start", "help"):
        send_telegram(HELP_TEXT, chat_id=ALLOWED_USER_ID)
    elif cmd in ("list", "queue"):
        send_telegram(_queue_summary(progress), chat_id=ALLOWED_USER_ID)


def ingest_user_words(progress):
    """Read new DMs from ALLOWED_USER_ID, queue any words, DM back a confirmation.

    Never raises — a Telegram hiccup here must not block the daily lesson.
    Returns the list of newly-queued (word, language) tuples.
    """
    try:
        updates = fetch_new_messages(progress.get("update_offset", 0))
    except Exception as e:
        print(f"Word ingestion skipped (getUpdates failed): {e}")
        return []

    existing = {(item["word"].lower(), item["language"]) for item in progress["queue"]}
    known_vocab = {w.lower() for w in progress["vocab"]}
    newly_queued, duplicates = [], []
    max_id = progress.get("update_offset", 0)

    for u in updates:
        max_id = max(max_id, u.get("update_id", 0))
        msg = u.get("message") or {}
        sender_id = (msg.get("from") or {}).get("id")
        if sender_id != ALLOWED_USER_ID:
            continue   # the bot reacts to nobody but you
        text = (msg.get("text") or "").strip()
        if not text:
            continue
        if text.startswith("/"):
            handle_command(text, progress)
            continue
        for word, lang in parse_added_words(text):
            key = (word.lower(), lang)
            if key in existing or word.lower() in known_vocab:
                duplicates.append((word, lang))
                continue
            existing.add(key)
            progress["queue"].append({
                "word": word, "language": lang, "added": date.today().isoformat()
            })
            newly_queued.append((word, lang))

    progress["update_offset"] = max_id

    if newly_queued:
        lines = ["✅ <b>Queued for your upcoming lessons:</b>"]
        lines += [f"• {esc(w)} {LANG_FLAGS.get(l, '')}" for w, l in newly_queued]
        if duplicates:
            dup = ", ".join(esc(w) for w, _ in duplicates)
            lines.append(f"\n<i>Skipped (already known/queued): {dup}</i>")
        try:
            send_telegram("\n".join(lines), chat_id=ALLOWED_USER_ID)
        except Exception as e:
            print(f"Could not send queue confirmation: {e}")
        print(f"Queued {len(newly_queued)} new word(s) from Telegram.")

    return newly_queued


# --------------------------------------------------------------------------- #
#  CLAUDE
# --------------------------------------------------------------------------- #
def generate_lesson(german_counts, added_words, review_words, known_words, grammar_topic):
    headers = {
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
    }
    payload = {
        "model": MODEL,
        "max_tokens": MAX_TOKENS,
        "temperature": TEMPERATURE,
        "system": SYSTEM_PROMPT,
        "messages": [{
            "role": "user",
            "content": build_user_message(german_counts, added_words, review_words, known_words, grammar_topic),
        }],
    }

    resp = requests.post(ANTHROPIC_URL, headers=headers, json=payload, timeout=120)
    resp.raise_for_status()
    data = resp.json()

    raw = "".join(block.get("text", "") for block in data.get("content", []))
    raw = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw.strip()).strip()

    lesson = json.loads(raw)
    if "new_words" not in lesson:
        raise ValueError("Lesson JSON missing 'new_words'.")
    return lesson


# --------------------------------------------------------------------------- #
#  FORMATTING -> list of Telegram-safe HTML messages
# --------------------------------------------------------------------------- #
def esc(text):
    """Escape user/AI text for Telegram HTML parse mode."""
    return html.escape(str(text or ""), quote=False)


def esc_md(text):
    """Escape for Telegram HTML, then turn any **markdown bold** the model
    slipped in into real <b> tags (asterisks don't survive HTML parse mode)."""
    return re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", esc(text))


def _display_headword(w):
    """Article + word (de/it), or word + reading (ja), or bare word (en)."""
    word = (w.get("word") or "").strip()
    article = (w.get("article") or "").strip() or None
    if article and word.lower().startswith(article.lower() + " "):
        word = word[len(article) + 1:]
    display = f"{article} {word}" if article else word
    reading = (w.get("reading") or "").strip()
    if reading:
        display += f" ({reading})"
    return display


def format_word_block(tag_emoji, index, w):
    lang = w.get("language", "de")
    flag = LANG_FLAGS.get(lang, "")

    header = f"<b>{tag_emoji} {index}. {esc(_display_headword(w))}</b> {flag}"
    plural = w.get("plural")
    if plural:
        header += f"  <i>(Pl. {esc(plural)})</i>"
    level = (w.get("level") or "").strip()
    if level:
        header += f"  [{esc(level)}]"

    lines = [header]
    synonyms = [s.strip() for s in (w.get("synonyms") or []) if s and s.strip()]
    if synonyms:
        lines.append(f"🔗 <i>{esc(', '.join(synonyms))}</i>")
    lines.append(f"➡️ {esc(w.get('english'))}")
    if INCLUDE_TURKISH and w.get("turkish"):
        lines.append(f"🇹🇷 {esc(w.get('turkish'))}")
    if w.get("usage"):
        lines.append(f"💡 <i>{esc(w['usage'])}</i>")
        if INCLUDE_TURKISH and w.get("usage_tr"):
            lines.append(f"🇹🇷 <i>{esc(w['usage_tr'])}</i>")

    fam_parts = []
    for fw in (w.get("family") or []):
        word = (fw.get("word") or "").strip()
        if not word:
            continue
        gloss = (fw.get("english") or "").strip()
        fam_parts.append(f"{esc(word)} ({esc(gloss)})" if gloss else esc(word))
    if fam_parts:
        lines.append(f"🌳 <i>{', '.join(fam_parts)}</i>")

    lines.append("")
    for ex in w.get("examples", []):
        lines.append(f"▪️ {esc(ex.get('target') or ex.get('de'))}")
        reading = (ex.get("reading") or "").strip()
        if reading:
            lines.append(f"   🔊 <i>{esc(reading)}</i>")
        if lang != "en":   # the example already IS English; no gloss needed
            lines.append(f"   ↳ {esc(ex.get('en'))}")
        if INCLUDE_TURKISH and ex.get("tr"):
            lines.append(f"   🇹🇷 {esc(ex.get('tr'))}")
    return "\n".join(lines)


def format_grammar_tip(tip):
    lines = ["📐 <b>Grammatik-Tipp</b>"]
    if tip.get("topic"):
        lines.append(f"<i>{esc(tip['topic'])}</i>")
    lines.append("")
    lines.append(esc_md(tip.get("explanation", "")))
    if INCLUDE_TURKISH and tip.get("explanation_tr"):
        lines.append(f"🇹🇷 {esc_md(tip['explanation_tr'])}")
    examples = tip.get("examples", [])
    if examples:
        lines.append("")
        for ex in examples:
            lines.append(f"▪️ {esc(ex.get('target') or ex.get('de'))}")
            lines.append(f"   ↳ {esc(ex.get('en'))}")
            if INCLUDE_TURKISH and ex.get("tr"):
                lines.append(f"   🇹🇷 {esc(ex.get('tr'))}")
    return "\n".join(lines)


def build_messages(lesson):
    langs_today = sorted(
        {w.get("language", "de") for w in lesson.get("new_words", []) + lesson.get("review_words", [])}
    )
    flags = "".join(LANG_FLAGS.get(l, "") for l in langs_today) or "🇩🇪"
    header = f"📚 <b>Wörter des Tages</b> {flags}\n\n"

    sections = []
    for i, w in enumerate(lesson.get("new_words", []), 1):
        sections.append(format_word_block("🆕", i, w))
    for i, w in enumerate(lesson.get("review_words", []), 1):
        sections.append(format_word_block("🔁", i, w))

    grammar_tip = lesson.get("grammar_tip")
    if grammar_tip:
        sections.append(format_grammar_tip(grammar_tip))

    messages = []
    current = header
    for section in sections:
        candidate = current + section + "\n\n"
        if len(candidate) > SAFE_CHUNK:
            messages.append(current.rstrip())
            current = section + "\n\n"
        else:
            current = candidate
    if current.strip():
        messages.append(current.rstrip())

    return messages


# --------------------------------------------------------------------------- #
#  VOICE  ->  one script per language, spoken via Edge TTS
# --------------------------------------------------------------------------- #
def collect_scripts_by_language(lesson):
    """Group target-language text (headwords + example sentences) by language.
    English glosses are never included. Returns {lang: script_text}."""
    scripts = {lang: [] for lang in SUPPORTED_LANGS}

    for w in lesson.get("new_words", []) + lesson.get("review_words", []):
        lang = w.get("language", "de")
        if lang not in scripts:
            continue
        headword = _display_headword(w)
        # drop the parenthetical romaji/reading from what we SPEAK
        headword = re.sub(r"\s*\(.*\)\s*$", "", headword).strip()
        if headword:
            scripts[lang].append(f"{headword}.")
        for ex in w.get("examples", []):
            target = (ex.get("target") or ex.get("de") or "").strip()
            if target:
                scripts[lang].append(target)

    # grammar tip examples are always German
    for ex in (lesson.get("grammar_tip") or {}).get("examples", []):
        target = (ex.get("target") or ex.get("de") or "").strip()
        if target:
            scripts["de"].append(target)

    return {lang: "\n".join(lines) for lang, lines in scripts.items() if lines}


async def _synthesize_mp3(text, voice, mp3_path):
    communicate = edge_tts.Communicate(text, voice=voice)
    await communicate.save(mp3_path)


def synthesize_voice(text, voice):
    """Target-language text -> ogg/opus bytes (Telegram voice-note format)."""
    with tempfile.TemporaryDirectory() as tmp:
        mp3_path = os.path.join(tmp, "voice.mp3")
        ogg_path = os.path.join(tmp, "voice.ogg")

        asyncio.run(_synthesize_mp3(text, voice, mp3_path))

        subprocess.run(
            ["ffmpeg", "-y", "-i", mp3_path,
             "-c:a", "libopus", "-b:a", "48k", "-ar", "48000", "-ac", "1",
             ogg_path],
            check=True, capture_output=True,
        )

        with open(ogg_path, "rb") as f:
            return f.read()


# --------------------------------------------------------------------------- #
#  TELEGRAM
# --------------------------------------------------------------------------- #
def send_telegram(text, chat_id=None):
    url = TELEGRAM_API_BASE.format(token=TELEGRAM_BOT_TOKEN, method="sendMessage")
    payload = {
        "chat_id": chat_id or TELEGRAM_CHAT_ID,
        "text": text,
        "parse_mode": "HTML",
        "disable_web_page_preview": True,
    }
    resp = requests.post(url, json=payload, timeout=30)
    resp.raise_for_status()
    return resp.json()


def send_telegram_voice(ogg_bytes, caption=None, chat_id=None):
    url = TELEGRAM_API_BASE.format(token=TELEGRAM_BOT_TOKEN, method="sendVoice")
    data = {"chat_id": chat_id or TELEGRAM_CHAT_ID}
    if caption:
        data["caption"] = caption
    files = {"voice": ("lesson.ogg", ogg_bytes, "audio/ogg")}
    resp = requests.post(url, data=data, files=files, timeout=60)
    resp.raise_for_status()
    return resp.json()


# --------------------------------------------------------------------------- #
#  LESSON ASSEMBLY  (shared by --once and --dry-run)
# --------------------------------------------------------------------------- #
def plan_lesson(progress):
    """Decide today's word mix from the queue + SRS state. Returns a dict of
    everything needed to generate and later record the lesson."""
    vocab = progress["vocab"]

    review_words = get_due_review_words(vocab, REVIEW_PER_DAY_TARGET)

    # your queued words first, in the order you added them
    added_words = [
        {"word": item["word"], "language": item["language"]}
        for item in progress["queue"][:WORDS_PER_DAY]
    ]

    # top up remaining slots with auto-generated German
    remaining = WORDS_PER_DAY - len(added_words)
    german_counts = {"A2": 0, "B1": 0, "B2": 0}
    for lvl in GERMAN_AUTO_SLOTS[:remaining]:
        german_counts[lvl] += 1

    known_words = [w for w, info in vocab.items() if info.get("language", "de") == "de"]
    grammar_topic = GRAMMAR_TOPICS[progress["grammar_index"] % len(GRAMMAR_TOPICS)]

    return {
        "german_counts": german_counts,
        "added_words": added_words,
        "review_words": review_words,
        "known_words": known_words,
        "grammar_topic": grammar_topic,
        "consumed_from_queue": len(added_words),
    }


def send_voice_notes(lesson):
    scripts = collect_scripts_by_language(lesson)
    for lang, text in scripts.items():
        if not text.strip():
            continue
        voice = VOICES.get(lang)
        if not voice:
            continue
        try:
            ogg_bytes = synthesize_voice(text, voice)
            caption = f"{LANG_FLAGS.get(lang, '')} {LANG_NAMES.get(lang, lang)}" if len(scripts) > 1 else None
            send_telegram_voice(ogg_bytes, caption=caption)
            print(f"Voice note sent ({lang}).")
        except Exception as e:
            # Non-fatal: a TTS/ffmpeg hiccup shouldn't block the text lesson.
            print(f"Voice note failed for {lang}, continuing: {e}")


# --------------------------------------------------------------------------- #
#  ORCHESTRATION
# --------------------------------------------------------------------------- #
def run_once():
    if not (TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID and ANTHROPIC_API_KEY):
        raise SystemExit(
            "Missing credentials. Set TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID, "
            "and ANTHROPIC_API_KEY in your .env file (local) or GitHub Secrets (cloud)."
        )

    progress = load_progress()

    # 1) read your DMs and queue any words you added since the last run
    ingest_user_words(progress)
    save_progress(progress)   # persist offset + queue before the heavier work

    # 2) plan today's mix (your words first, German top-up, due reviews)
    plan = plan_lesson(progress)
    mix = ", ".join(f"{n}x{lvl}" for lvl, n in plan["german_counts"].items() if n > 0) or "none"
    print(f"Added words: {len(plan['added_words'])}, German auto: {mix}, "
          f"reviews: {len(plan['review_words'])}, grammar: {plan['grammar_topic']}")

    lesson = generate_lesson(
        plan["german_counts"], plan["added_words"], plan["review_words"],
        plan["known_words"], plan["grammar_topic"],
    )

    # only trust review items that match something we actually asked to review
    review_keys = {(r["word"], r["language"]) for r in plan["review_words"]}
    review_items = [
        w for w in lesson.get("review_words", [])
        if ((w.get("word") or "").strip(), w.get("language", "de")) in review_keys
    ]
    missing = review_keys - {((w.get("word") or "").strip(), w.get("language", "de")) for w in review_items}
    if missing:
        print(f"Note: model skipped reviews for: {missing} (will retry next run)")
    lesson["review_words"] = review_items

    messages = build_messages(lesson)
    print(f"Sending {len(messages)} message(s) to Telegram...")
    for i, msg in enumerate(messages):
        send_telegram(msg)
        if i < len(messages) - 1:
            time.sleep(1)   # gentle pacing, avoids rate limits

    if ENABLE_VOICE:
        send_voice_notes(lesson)

    # 3) record state: newly-taught words enter the SRS store; consume the queue
    taught = lesson.get("new_words", [])
    update_vocab_after_send(progress["vocab"], taught, review_items, plan["review_words"])
    progress["queue"] = progress["queue"][plan["consumed_from_queue"]:]
    progress["grammar_index"] = (progress["grammar_index"] + 1) % len(GRAMMAR_TOPICS)
    save_progress(progress)

    print(f"Done. Vocab store: {len(progress['vocab'])} word(s). "
          f"Queue remaining: {len(progress['queue'])}. "
          f"Next grammar topic: {GRAMMAR_TOPICS[progress['grammar_index']]}")


def run_dry_run():
    """Build a sample lesson exercising all four languages, print it, send NOTHING.
    Uses the Anthropic API but never touches Telegram or progress.json."""
    if not ANTHROPIC_API_KEY:
        raise SystemExit("Dry run needs ANTHROPIC_API_KEY set (in .env).")

    added_words = [
        {"word": "frigorifero", "language": "it"},
        {"word": "食べる", "language": "ja"},
        {"word": "reliable", "language": "en"},
    ]
    remaining = WORDS_PER_DAY - len(added_words)
    german_counts = {"A2": 0, "B1": 0, "B2": 0}
    for lvl in GERMAN_AUTO_SLOTS[:remaining]:
        german_counts[lvl] += 1

    print(f"[dry-run] added={added_words}, german={german_counts}")
    lesson = generate_lesson(german_counts, added_words, [], [], GRAMMAR_TOPICS[0])

    print("\n===== TELEGRAM MESSAGES (not sent) =====\n")
    for msg in build_messages(lesson):
        print(msg)
        print("\n----- (message break) -----\n")

    scripts = collect_scripts_by_language(lesson)
    print("===== VOICE NOTES THAT WOULD BE SENT =====")
    for lang, text in scripts.items():
        print(f"\n[{lang}] voice={VOICES.get(lang)}\n{text}")
    print("\n[dry-run] Nothing was sent to Telegram; progress.json untouched.")


def run_scheduled():
    import schedule
    schedule.every().day.at(SEND_TIME).do(run_once)
    print(f"Scheduler running. Daily send at {SEND_TIME}. Ctrl+C to stop.")
    while True:
        schedule.run_pending()
        time.sleep(30)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Daily multi-language reactivation Telegram bot (German-focused)")
    parser.add_argument("--once", action="store_true",
                        help="Generate and send a single lesson now, then exit.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Build a sample lesson and print it without sending anything.")
    args = parser.parse_args()

    if args.dry_run:
        run_dry_run()
    elif args.once:
        run_once()
    else:
        run_scheduled()
